### ISSUE TITLE
код приходит в кавычках

### ISSUE THREAD

**Issue by indpnnd** [Petrovich-Z/gss4tilda#1]
пытаюсь импортировать в тильдовскую таблицу изображение <img..> – Гугл отдает этот код в "кавычках" почему-то, и в итоге в тильду приходит просто текст.

при этом сам блок тильды "таблица" изображения поддерживает, если вставить <img> через стандартный редактор тильды.

**Comment by Petrovich-Z** [comment]
Пришлите ссылку на тестовую гугл таблицу, попробую разобраться. У меня ни разу подобной задачи не возникало.

**Comment by indpnnd** [comment]
Добрый день!

Вот ссылка: https://project1034476.tilda.ws/table <https://bonz.app/table>

**Comment by Petrovich-Z** [comment]
Пришлите ссылку на тестовую гугл таблицу, попробую разобраться. У меня ни разу подобной задачи не возникало.

**Comment by indpnnd** [comment]
https://docs.google.com/spreadsheets/d/1l1lQCV22xs1lSxDMVj_HBMOeECk3HP6EtE48i59PfNY/edit?usp=sharing

**Comment by Petrovich-Z** [comment]
В общем все дело в том, что перед выводом информации скрипт экранирует все символы. Чтобы например знак больше в тексте ячейки не сломал верстку. Чтобы это  обойти можно использовать не минимизированный код, вставить его непосредственно в html элемент тильды (подключать скрипт с jsdelivr.net тогда не нужно) и заменить строку `part2 += htmlentities(data.table.rows[i].c[j].v) + ';'` на `part2 += data.table.rows[i].c[j].v + ';'`
Но будьте осторожны с текстом в остальных ячейках. Ну или можно например выбарать какие столбцы фильтровать, а какие нет по номеру столбца.

**Comment by indpnnd** [comment]
Спасибо большое! Изучу

**Comment by Petrovich-Z** [comment]
Рабочий пример тут
http://portfolio-z.tilda.ws/gsstest

**Comment by Petrovich-Z** [comment]
Рад помочь
